Removes JS 2021 only function and makes compatible back to JS 2015
This change allows some older iPads to use the app and prevent the

> ERRORTypeError: v.replaceAll is not a function. (In 'v.replaceAll(/[BE]/g,(function(e){return(z?"EB":"BE")["BE".indexOf(e)]}))', 'v.replaceAll' is undefined

JS error from causing a blank screen to be shown on them.